languageCode: "en-us"
title: "Nishchay's Portfolio"
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: https://medium.com/@nishchay.vns2000
      weight: 1

params:
  title: "Nishchay's Portfolio"
  description: "Cool"
  favicon: "/images/me.jpeg"

  theme:
    disableThemeToggle: false

  font:
    fontSize: 1.2rem
    fontWeight: 300
    lineHeight: 1.2
    textAlign: left

  darkmode:
    textColor: 'blue'
    secondaryTextColor: 'gray'

  navbar:
    align: mx-auto
    brandLogo: "/images/portfolio.png"
    brandName: "Portfolio"

  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Nishchay."
    subtitle: "I build robust and scalable software solutions"
    content: "A dedicated Software Engineer with experience in developing robust applications and system design. I leverage modern technologies to create efficient, reliable, and maintainable software systems."
    image: /images/hero.svg
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1nHKmiSC-c5vt7zC4eLt2LY_XX7u96_6x/view?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://www.github.com/codernishchay
        - icon: fab fa-twitter
          url: https://www.twitter.com/nishchay_v_

  # Experience
  experience:
    enable: true
    items:
      - job: "Software Engineer"
        company: "Teacher Tools Private Limited"
        date: "Jan 2023 - Present"
        featuredLink:
          enable: true
        content: |-
          - Enhanced Lambda cold start time by up to 20% through optimization of dataloaders and removal of dead GraphQL endpoints, resulting in a leaner codebase and faster execution.
          - Monitored and optimized database queries, achieving significant improvements in overall system efficiency and response times.
          - Revamped OpenAPI V1 and implemented OpenAPI V2, enhancing user experience and optimizing code structure for better maintainability.
          - Developed scripts and packages to automate redundant tasks, significantly improving development efficiency and streamlining processes.
          - Implemented multiple integrations for various features within platforms, utilized by thousands of users, enhancing functionality and user satisfaction.

      - job: "Software Engineer Intern"
        company: "Sozo.Finance"
        date: "Sept 2022 - Jan 2023"
        featuredLink:
          enable: true
        content: |-
          - Spearheaded the development of a fully functional web application for a DeFi wallet utilizing Golang and React.js.
          - Designed and implemented robust deployment strategies, integrating advanced analytics and optimizing CI/CD processes to enhance the reliability and efficiency of software delivery.

      - job: "Software Engineer Intern"
        company: "Newton School"
        date: "Apr 2023 - May 2023"
        featuredLink:
          enable: true
        content: |-
          - Streamlined development processes, reducing code redundancy and fostering the creation of reusable components.
          - Developed a widely-utilized SQL playground with SQL course materials, including over 350 problems.
          - Implemented the Cypress testing framework, resulting in efficiency gains and reduced development costs.

  # Education
  education:
    enable: true
    index: true
    items:
      - title: "Bachelor of Engineering in Electrical and Electronics"
        school:
          name: "Indian Institute of Information Technology"
          url: "https://iiits.ac"
        date: "Aug 2019 - Jul 2023"
        GPA: "CGPA: 7.10"
        featuredLink:
          enable: false

      - title: "12th"
        school:
          name: "Bal Vidyalaya Madhyamik School"
        date: "Aug 2016 - Jul 2018"
        GPA: "Percentage: 83%"
        featuredLink:
          enable: false

  # Achievements
  achievements:
    enable: true
    items:
      - title: "Google Hash Code"
        content: "Secured All India Rank (AIR) 418 and Global Rank 1593 out of over 20,000 participating teams"

      - title: "LeetCode"
        content: "Ranked in the top 11% globally with a maximum score of 1773 points and completed over 500 coding challenges"

      - title: "HackerRank"
        content: "Earned 4 stars in SQL and 4 stars in Problem Solving"

  # Projects
  projects:
    enable: true
    items:
      - title: "Urban Eatary"
        content: "Developed a comprehensive food delivery website with a secure role-based access control system using JWT authentication and an admin panel for efficient management of items and restaurant operations."
        image: /images/foodie.png
        featured:
          name: "Live Demo"
          link: "https://urban-eatary-front.web.app"
        badges:
          - "React.js"
          - "Firebase"
          - "CSS"
          - "Node.js"
          - "JWT"
        links:
          - icon: fab fa-github
            url: https://github.com/vnishchay/Urban-Eatary-Frontend

      - title: "Interview Zone"
        content: "Engineered a cutting-edge interview platform with real-time video calling using peer.js and robust bidirectional messaging with socket.io for dynamic user interactions."
        image: /images/interview-zone.png
        featured:
          name: "GitHub"
          link: "https://github.com/interview-zone"
        badges:
          - "Node.js"
          - "React.js"
          - "WebRTC"
          - "WebSocket"
          - "MongoDB"
          - "Mongoose"

      - title: "SuperMarket Covid ABM"
        content: "Developed a sophisticated agent-based model for analyzing COVID-19 spread in supermarkets using NetLogo and GIS."
        image: /images/netlogo.png
        featured:
          name: "GitHub"
          link: "https://github.com/vnishchay/supermkt-covid-abm"
        badges:
          - "NetLogo"
          - "GIS"
          - "GitHub"

      - title: "Neuresta"
        content: "Created a web application for generating neurostyled images from two input images using Django and Python."
        image: /images/neuresta.png
        featured:
          name: "GitHub"
          link: "https://github.com/Shreyas-MS/WAD_NST"
        badges:
          - "HTML"
          - "CSS"
          - "JavaScript"
          - "Django"
          - "Python"

  # Contact
  contact:
    enable: true
    content: "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
    email: nishchay.vns2000@gmail.com
    btnName: "Mail me"

  footer:
    socialNetworks:
      github: https://github.com/vnishchay
      linkedin: https://www.linkedin.com/in/vnishchay/
      twitter: https://twitter.com/nishchay_v_
      instagram: https://instagram.com/nishchay_v_
