languageCode: "en-us"
title: "Nishchay's Portfolio"
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: https://medium.com/@nishchay.vns2000
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 2
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Nishchay's Portfolio"
  description: Cool 
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/me.jpeg"

  theme:
    disableThemeToggle:
    # defaultTheme: "light" # dark

  font:
    fontSize: 1.2rem # default: 1rem
    fontWeight: 300 # default: 400
    lineHeight: 1.2 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

    darkmode:
      textColor: 'blue'
      secondaryTextColor: 'gray'
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/images/portfolio.png" # Logo for the brand | default is the favicon variable
    brandName: "Portfoio" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Nishchay."
    subtitle: "I build things for the web"
    content: "A passionate web app developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
    image: /images/hero.svg
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1dU8fit6SoKinfZl-Tt_QgCGxaxDNYPLr/view?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://www.github.com/codernishchay
        - icon: fab fa-twitter
          url: https://www.twitter.com/nishchay_v_
      

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpeg"
    content: |-
             Hi, I'm a Computer Science student who loves to build fast and effecient apps. 
    skills:
      enable: true
      title: "few technologies I've been working with recently are:"
      items:
        - "JavaScript"
        - "Golang"
        - "Flutter"
        - "C++"
        - "SQL"
        - "Mongodb"

  # Experience
  experience:
    enable: true
    items:
      - job: "Software Development Intern"
        company: "Wink.finance"
        # companyUrl: "https://example.com"
        date: "Sep 2022 - current"
        featuredLink:
          enable: true
          # url: "https://play.google.com/store/apps/details?id=ml.campusmedia.userapp"
        info:
          enable: true
        content: Working with Smart contract and UI/UX team to create the web3 project.
        # content: 
      - job: "Technical Content Intern"
        company: "Newton School"
        companyUrl: "https://www.newtonschool.co/computerscience?utm_source=Ads&utm_medium=CS_Googlesmart+ADs&utm_campaign=Mia_CS_Googlesmart+ADs&gclid=CjwKCAjwquWVBhBrEiwAt1Kmwhrb70w4IRvw-uuclQ7GH0IgV5jWMWunQOaMxOxK8wRnB8ESHkoVtBoCWkYQAvD_BwE"
        date: "Jan 2022 - present"
        featuredLink:
          enable: false
          # name: "View the project"
          # url: "https://example.com"
        content: "- Worked closely with the design team to create a user-friendly and visually appealing landing page and cryptocurrency exchange frontend from scratch.
- Utilized a range of development skills, including HTML, CSS, JavaScript, and React, to build the frontend and ensure a smooth user experience.
- Collaborated with the blockchain team to integrate the exchange frontend with the underlying blockchain infrastructure, ensuring seamless functionality and security for users."

      - job: "Android Developer"
        company: "Campus Media"
        # companyUrl: "https://example.com"
        date: "Feb 2020 - Apr 2021"
        featuredLink:
          enable: true
          url: "https://play.google.com/store/apps/details?id=ml.campusmedia.userapp"
        info:
          enable: true
        content: Worked on Campus Media application as a software developer intern. Created firebase functions, managed firebase backend and created/fixed features on the application.
        # content: 
      


    
  # Education
  education:
    enable: true
    index: true
    items:
      - title: "B.Tech Computer Science and Engneering"
        school:
          name: "Indian Institute of Information Technology Sricity"
          url: "https://iiits.ac"
        date: "2019 - 2023"
        # GPA: "3.8 out of 5.0"
        content: |-
          Currently Attending my last year at institute

          Extracurricular Activities
            - Created two major projects. 
            - Lead Blogs and Podcasts team at IOTA

      - title: "Intermediate"
        school:
          name: "Bal Vidyalaya Madhyamik School"
          url : "" 
        date: "2016 - 2018"
        GPA : "81.5%"
        featuredLink:
          enable: false
      
      - title : "High School"
        school:
          name: "D.A.V Public School"
          url: " "
        date : "2015-2016"
        GPA: "8.8 out of 10"
        featuredLink:
          enable: false
          url: ""

  # Achievements
  achievements:
    enable: true
    items:
      - title: Google Hash Code 
        content: Secured AIR 417 and 1513 Global rank 
        # url: https://example.com

      - title: Geeks for Geeks Jobathon 
        content: Secured AIR 49  
        # url: https://example.com
      
      #  - title:  
      #   content: Secured AIR 417 and 1513 Global rank 
      #   # url: https://example.com
    
   
   
    
  # projects
  projects:
    enable: true
    items:
      - title: Interviwe Zone
        content: An interview website, where people can connect and conduct interview
        image: /images/interview-zone.png
        featured:
          name: Github
          link: https://github.com/codernishchay/interview-zone
        badges:
          - "Node.js"
          - "React.js"
          - "WebRtc"
          - "Websocket"
          - "MongoDB"
          - "Mongoose"
      
      - title: Urban Eatary
        content: A food delivery website with awesome UI and admin panel.
        image: /images/foodie.png
        featured:
          name: Demo
          link: https://foodie-eb5cd.web.app
        badges:
          - "React.js"
          - "Firebase"
          - "CSS"
          - "Node.js"
          - "JWT"
        links:
          - icon: fab fa-github
            url: https://github.com/codernishchay/urban-eatary-frontend


      - title: SuperMarket Covid ABM
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/netlogo.png
        featured:
          name: Github
          link: https://github.com/codernishchay/supermkt-covid-abm
        badges:
          - "Netlogo"
          - "GIS"
          - "Github"
        links:
      
      - title: Neuresta
        content: A website to generate neurostyled images out of two input images.
        image: /images/neuresta.png
        featured:
          name: Github
          link: https://github.com/Shreyas-MS/WAD_NST
        badges:
          - "HTML"
          - "CSS"
          - "Javascript"
          - "Django"
          - "Python"
        links:
      
         
      

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: nishchay.vns2000@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/codernishchay
      linkedin: https://www.linkedin.com/in/codernishchay/
      twitter: https://twitter.com/nishchay_v_
      instagram: https://instagram.com/nishchay_v_